config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'
  
  devise_for :users
  
  resources :accounts do
    collection do
      get '/deposit', action: 'deposit'
      post '/create_deposit', action: 'create_deposit'
      get '/transfer', action: 'transfer'
      post '/create_transfer', action: 'create_transfer'
      get '/withdraw', action: 'withdraw'
      post '/create_withdraw', action: 'create_withdraw'
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "pages/home"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :operations_origin,class_name: 'Operation', foreign_key: :origin_id
  has_many :operations_destiny,class_name: 'Operation', foreign_key: :destiny_id

  enum status: { inactive: 0, active: 1}

  # validations
  validates :number,:agency, :status, presence: true
  validates :number, uniqueness: true

  #methods
  def check_balance
    self.balance = self.user.balance
  end

  def check_agency
    self.agency = self.user.agency
  end

  def check_status
    self.status = self.user.status
  end

  def check_user
    self.user = User.find(self.number)
  end

  def deposit(value)
    if value > 0
      self.balance += value
      save
      Operation.create(kind: :deposit, value: value, destiny_id: self.id)
    else
      raise "Valor inválido"
    end
  end

  def transfer(value, account)
    if self.balance >= value && self.id != account.id
      total_value = 0
      if ([0,6].exclude?(Time.current.wday) && (Time.now.hour >= 9 && Time.now.hour < 18))
        total_value = value + 5
      else
        total_value = value + 7
      end
      total_value += 10 if value > 1000
      update(balance: self.balance -= total_value)
      account.update(balance: account.balance += value)
      Operation.create(kind: :transfer, value: value, origin_id: self.id, destiny_id: account.id)
    else
      raise "Saldo insuficiente ou conta igual a de destino"
    end
  end

  def withdraw(value)
    if self.balance >= value
      self.balance -= value
      save
      Operation.create(kind: :withdraw, value: value, origin_id: self.id)
    else
      raise "Saldo insuficiente"
    end
  end

  def statement_by_period(initial_date, final_date)
    Statement.where(account_id: self.id, date: initial_date..final_date)
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :origin, class_name: 'Account', optional: true
  belongs_to :destiny, class_name: 'Account', optional: true
  enum kind: { deposit: 0, transfer: 1, withdraw: 2}

  scope :interval, ->(created_at, updated_at) { where(created_at: created_at..updated_at) }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :accounts, dependent: :destroy
  after_create :create_account

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # validations
  validates :cpf, :name, :email,:birthday, presence: true
  validates :cpf, uniqueness: true
  validates :email, uniqueness: true


  def create_account
    loop do
      account_number = rand(1000000..9999999)
      unless Account.exists?(number: account_number)
        Account.create(user_id: self.id, number: account_number, agency: 2448, balance: 0.0)
        break
      end
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :can_search, only: %i(show)


  def index
    @accounts = Account.all
  end

  def show
    authorize @account
    @account = Account.find(params[:id])
    @operations = []
    @operations = Operation.where(created_at: Time.parse(params[:start_date])..Time.parse(params[:end_date]))
                           .where("origin_id = ? OR destiny_id = ?", @account.id, @account.id) if @can_search
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def edit 
  end

  
  def update 
    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy 
    @account.update(status: ":inactive")
    redirect_to accounts_path
  end

  def deposit
    
  end

  def create_deposit
    @account = Account.find(params[:id])
    @account.deposit(params[:value].to_d)
    redirect_to dashboard_index_path
  end

  def transfer
  end

  def create_transfer
    @account = Account.find(params[:id])
    destiny_account = Account.find_by(number: params[:number])
    if destiny_account.present?
      @account.transfer(params[:value].to_d, destiny_account)
      redirect_to dashboard_index_path
    else
      render :transfer
    end
  end

  def withdraw
  end

  def create_withdraw
    @account = Account.find(params[:id])
    @account.withdraw(params[:value].to_d)
    redirect_to dashboard_index_path
  end



  private

  def set_account
    @account = Account.find(params[:id])
    authorize @account
  end

  def account_params
    params.require(:account).permit(:saldo, :number, :agency, :status,:user_id)
  end

  def can_search
    @can_search = false
    return unless (params[:start_date].present? && params[:end_date].present?)
    @can_search = (Time.parse(params[:start_date]) rescue nil).present? && (Time.parse(params[:end_date]) rescue nil).present?
    if @can_search
      @can_search = Time.parse(params[:start_date]) < Time.parse(params[:end_date])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation, :cpf, :birthday)
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    dashboard_index_path
  end

  private 

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar esta ação."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @account = Account.find_by(user_id: current_user.id)
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  
  def home
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_date(date)
    date.strftime("%d - %b %Y  %H:%M")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/_form.html.erb
<%= form_tag create_deposit_accounts_path do %>
  <div id="root">
    <div class="App background">
      <div id="db-wrapper">
        <div class="d-flex flex-column container">
          <div class="align-items-center justify-content-center g-0 min-vh-100 row">
            <div class="py-8 py-xl-0 col-lg-5 col-md-5">
              <div class="card">
                <div class="p-6 card-body">
                  <form class="">
                    <div class="row">
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:id, "Escolha sua conta:", class: "form-label") %>
                        <%= select_tag(:id, options_for_select(current_user.accounts.collect{|a| [a.number, a.id] }),class: "form-control-input ") %>
                        
                      </div>
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:value, "Digite o valor:", class: "form-label") %>
                        <%= number_field_tag(:value,"", class: "form-control-input") %>
                      </div>
                      
                      <div class="mb-0 d-grid gap-2 col-lg-12 col-md-12">
                        <%= submit_tag("Realizar Operação", class: "btn btn-primary") %>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/_form_date.html.erb
<%= form_tag @account, method: :get do %>
  <div id="root">
    <div class="App background">
      <div id="db-wrapper">
        <div class="d-flex flex-column container">
          <div class="align-items-center justify-content-center g-0 min-vh-100 row">
            <div class="py-8 py-xl-0 col-lg-5 col-md-5">
              <div class="card">
                <div class="p-6 card-body">
                  <form class="">
                    <div class="row">
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag 'Data Inicial', nil, class: 'form-label' %>
                        <%= date_field_tag 'start_date', params[:start_date], placeholder: "Enter Start Date",class: "form-control-input"%>
                      </div>
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag 'Data Final', nil, class: 'form-label' %>
                        <%= date_field_tag 'end_date', params[:end_date], placeholder: "Enter End Date",class: "form-control-input"%>
                      </div>
                      
                      <div class="mb-0 d-grid gap-2 col-lg-12 col-md-12">
                        <%= submit_tag("Realizar Operação", class: "btn btn-primary") %>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/_form_transfer.html.erb
<%= form_tag create_transfer_accounts_path do %>
  <div id="root">
    <div class="App background">
      <div id="db-wrapper">
        <div class="d-flex flex-column container">
          <div class="align-items-center justify-content-center g-0 min-vh-100 row">
            <div class="py-8 py-xl-0 col-lg-5 col-md-5">
              <div class="card">
                <div class="p-6 card-body">
                  <form class="">
                    <div class="row">
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:id, "Escolha sua conta:", class: "form-label") %>
                        <%= select_tag(:id, options_for_select(current_user.accounts.collect{|a| [a.number, a.id] }),class: "form-control-input ") %>
                      </div>
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:value, "Digite o valor:", class: "form-label") %>
                        <%= number_field_tag(:value,"", class: "form-control-input") %>
                      </div>

                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:number, "Digite a Conta De Destino:", class: "form-label") %>
                        <%= number_field_tag(:number,"", class: "form-control-input") %>
                      </div>
                      
                      <div class="mb-0 d-grid gap-2 col-lg-12 col-md-12">
                        <%= submit_tag("Realizar Operação", class: "btn btn-primary") %>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/_form_withdraw.html.erb
<%= form_tag create_withdraw_accounts_path do %>
  <div id="root">
    <div class="App background">
      <div id="db-wrapper">
        <div class="d-flex flex-column container">
          <div class="align-items-center justify-content-center g-0 min-vh-100 row">
            <div class="py-8 py-xl-0 col-lg-5 col-md-5">
              <div class="card">
                <div class="p-6 card-body">
                  <form class="">
                    <div class="row">
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:id, "Escolha sua conta:", class: "form-label") %>
                        <%= select_tag(:id, options_for_select(current_user.accounts.collect{|a| [a.number, a.id] }),class: "form-control-input ") %>
                        
                      </div>
                      <div class="mb-3 col-lg-12 col-md-12">
                        <%= label_tag(:value, "Digite o valor:", class: "form-label") %>
                        <%= number_field_tag(:value,"", class: "form-control-input") %>
                      </div>
                      
                      <div class="mb-0 d-grid gap-2 col-lg-12 col-md-12">
                        <%= submit_tag("Realizar Operação", class: "btn btn-primary") %>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/accounts/deposit.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <div class="container-xxl bg-white p-0">
    <%# Hero End %>
    <div class="container-xxl bg-primary hero-header">
      <%= render 'form', accounts: current_user.accounts %> 
    </div>
    <%# end hero %>

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
  </div>
</body>

</html>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>

app/views/accounts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <div class="container-xxl bg-white p-0">
    <div class="container-xxl bg-primary hero-header">
      <%= render 'form_date', accounts: current_user.accounts %> 
    </div>

    <% if @operations.present? %>
      <div class="card">
        <h5 class="card-header">Extract</h5>
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>Operation</th>
                <th>Value</th>
                <th>User_origin</th>
                <th>User_destiny</th>
                <th>Date_operation</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
            <% @operations.each do |operation| %>
              <tr>
                <td><strong><i class="fa-regular fa-dollar-sign"></i> <%= operation.kind%></strong></td>
                <td><%= operation.value %></td>
                <td><%= operation.try(:origin).try(:number)%></td>
                <td><%= operation.try(:destiny).try(:number) %></td>
                <td><%= log_date(operation.created_at) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <p>No operations found</p>
    <% end %>

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
  </div>
</body>

</html>

app/views/accounts/transfer.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <div class="container-xxl bg-white p-0">
    <%# Hero End %>
    <div class="container-xxl bg-primary hero-header">
      <%= render 'form_transfer', accounts: current_user.accounts %> 
    </div>
    <%# end hero %>

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
  </div>
</body>

</html>

app/views/accounts/withdraw.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <div class="container-xxl bg-white p-0">
    <%# Hero End %>
    <div class="container-xxl bg-primary hero-header">
      <%= render 'form_withdraw', accounts: current_user.accounts %> 
    </div>
    <%# end hero %>

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
  </div>
</body>

</html>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
    <div class="container-xxl bg-white p-0">

        <%# Hero End %>
        <div class="container-xxl bg-primary hero-header">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 text-center text-lg-start">
                        <h1 class="text-white mb-4 animated zoomIn ">Seja Bem vindo ,</br> <%= current_user.name %></h1>
                        <h3 class="text-white mb-4 animated zoomIn "> O seu saldo em suas contas:</h3>
                            <% current_user.accounts.each do |account| %> 
                            <h3 class="text-white mb-4 animated zoomIn "><%= account.number %> - <%= account.balance %> R$</h3>
                            <% end %>
                    </div>
                    <div class="col-lg-6 text-center text-lg-start">
                        <img class="img-fluid animated zoomIn" src="https://technext.github.io/bizconsult/img/hero.png" alt="">
                    </div>
                </div>
            </div>
        </div>
        <%# end hero %>


        <!-- Service Start -->
        <div class="container-xxl py-6">
            <div class="container">
                <div class="mx-auto text-center wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
                  <div class="d-inline-block border rounded-pill text-primary px-4 mb-3">Our Services</div>
                  <h2 class="mb-5">Realizar operações</h2>
                </div>
                <div class="row g-4">
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((pages_home_path),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"><i class="fa-sharp fa-5x fa-solid fa-house"></i></h5>
                            <h4 class="mb-3 text-center">Home</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((deposit_accounts_path),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"> <i class="fa-regular fa-5x fa-dollar-sign"></i></h5>
                            <h4 class="mb-3 text-center">Depósitos</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((transfer_accounts_path),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"><i class="fa-solid fa-5x fa-money-bill-transfer"></i></h5>
                            <h4 class="mb-3 text-center">Transferências</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((withdraw_accounts_path),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"><i class="fa-solid fa-5x fa-sack-dollar"></i></h5>
                            <h4 class="mb-3 text-center">Saques</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((@account),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"><i class="fa-solid fa-5x fa-book"></i></h5>
                            <h4 class="mb-3 text-center">Extratos</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                      <div class="service-item rounded h-100 box-field">
                        <%= link_to((edit_user_registration_path),class:"trash-button-header icons-dashboard link-box") do %>
                          <div class="p-5">
                            <h5 class="mb-3 text-center"><i class="fa-solid fa-5x fa-user"></i></h5>
                            <h4 class="mb-3 text-center">Gerenciar Perfil</h4>
                          </div>
                        <% end %>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Service End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
</body>

</html>

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 wow fadeIn" data-wow-delay="0.1s" style="margin-top: 6rem;">
      <div class="container">
          <div class="copyright">
              <div class="row">
                  <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                      &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                      <br>Distributed By: <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                  </div>
                  <div class="col-md-6 text-center text-md-end">
                      <div class="footer-menu">
                          <a href="">Home</a>
                          <a href="">Cookies</a>
                          <a href="">Help</a>
                          <a href="">FQAs</a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
    <!-- Footer End -->
<% end %>

app/views/layouts/_topnavbar.html.erb
<!-- Navbar & Hero Start -->
<div class="container-xxl position-relative p-0">
  <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
    <a href="/" class="navbar-brand p-0">
      <h1 class="m-0">BizConsult</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
      <span class="fa fa-bars"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <div class="navbar-nav ms-auto py-0">
        <%= link_to "Home", root_path,class: "nav-item nav-link active"%>
        <%= link_to "DashBoard", dashboard_index_path ,class: "nav-item nav-link"%>
        <%= link_to "Depósitos", deposit_accounts_path ,class: "nav-item nav-link"%>
        <% if user_signed_in? %>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Opções</a>
            <div class="dropdown-menu m-0">
              <%= link_to "Editar Perfil", edit_user_registration_path ,class: "dropdown-item"%>
              <%# <a href="feature.html" class="dropdown-item">Editar Perfil</a> %>
              <%= button_to("Sair",destroy_user_session_path,class:"dropdown-item",method: :delete) %> 
              <%# <a href="quote.html" class="dropdown-item">Sair</a> %>
              <%# <%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
) %> 
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>
<!-- Navbar & Hero End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <meta charset="utf-8">
    <title>BizConsult - Consulting HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/33a6f6a80f.js" crossorigin="anonymous"></script>
  </body>
</html>